### Arrays


####  Difference between arrays and lists is that every array element should be of the same data type

In [2]:
import numpy as np

In [4]:
a = np.array([[0,1,2,3], [4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
#NumPy n-dimensional array = ndarray and it is always homogenous.
#array() - returns a data structure in the Numpy array format

In [5]:
a.shape

(2, 4)

In [6]:
a[1,3]

7

In [8]:
a[1,2] = 8
a

array([[0, 1, 2, 3],
       [4, 5, 8, 7]])

In [9]:
a[0]

array([0, 1, 2, 3])

In [10]:
a[1]

array([4, 5, 8, 7])

In [ ]:
#A vector is an object that has both magnitude and direction

In [12]:
#1D array = vector
b = np.array([3,5])
b

array([3, 5])

In [ ]:
#2D array = matrix


### Generating Random Numbers

In [15]:
import random

In [17]:
prob = random.random()  #generates a random float in the range [0,1)
print(prob)

0.11589554594059948


In [18]:
number = random.randint(1,6)  #randomizes over a provided interval and delivers an integer value
number

6

In [19]:
import numpy as np

In [20]:
np.random.randint(1,6, (4,6))

array([[5, 5, 1, 2, 5, 5],
       [1, 1, 1, 3, 3, 2],
       [5, 4, 5, 4, 5, 3],
       [3, 5, 1, 3, 2, 4]])

### Importing and Organizing Your Data - Part 1

In [1]:
import numpy as np
import pandas as pd

In [3]:
# pd.Series() - single column data
ser = pd.Series(np.random.random(5), name = "Column 01")

In [4]:
ser

0    0.517758
1    0.035610
2    0.525629
3    0.290975
4    0.125898
Name: Column 01, dtype: float64

In [5]:
ser[2]

0.5256292833424319

In [ ]:
# pd.DataFrame() - several columns

In [6]:
from pandas_datareader import data as wb  #wb - web
#pandas_datareader is used to import data from web sources

In [8]:
PG = wb.DataReader('PG', data_source = 'yahoo', start = '1995-1-1')
#PG - Procter&Gamble, data_source - web server to extract data from, start - from start data till latest date 
#PG is a tikcer - every company has a symbol or code that it uses on stock exchage
#eg. Procter&Gamble - PG, Apple - AAPL, microsoft - 'MSFT'
#data - yyyy-m-d


#Data for saturdays, sundays and national holidays won't be quoted as the stock market is not open on those days i.e. trading days only

In [9]:
PG

High         Low        Open       Close     Volume  \
Date                                                                    
1995-01-03   15.625000   15.437500   15.468750   15.593750  3318400.0   
1995-01-04   15.656250   15.312500   15.531250   15.468750  2218800.0   
1995-01-05   15.437500   15.218750   15.375000   15.250000  2319600.0   
1995-01-06   15.406250   15.156250   15.156250   15.281250  3438000.0   
1995-01-09   15.406250   15.187500   15.343750   15.218750  1795200.0   
...                ...         ...         ...         ...        ...   
2021-08-11  143.240005  142.470001  142.740005  142.619995  4205000.0   
2021-08-12  143.149994  142.350006  143.149994  142.949997  4956100.0   
2021-08-13  143.990005  142.690002  142.949997  143.639999  4888300.0   
2021-08-16  144.690002  143.380005  143.669998  144.639999  6040800.0   
2021-08-17  145.600006  143.889999  144.399994  144.880005  7577000.0   

             Adj Close  
Date                    
1995-01-03    8.063840  
1995-01-04    7.999201  
1995-01-05    7.886079  
1995-01-06    7.902242  
1995-01-09    7.869921  
...                ...  
2021-08-11  142.619995  
2021-08-12  142.949997  
2021-08-13  143.639999  
2021-08-16  144.639999  
2021-08-17  144.880005  

[6704 rows x 6 columns]

In [11]:
PG.info() 
#datatype
#no.of entries, start date, end date (timesoan)
#no.of columns
#number of data points, for each column, here, no missing data and data types (Volume - int, rest - float)


<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6704 entries, 1995-01-03 to 2021-08-17
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   High       6704 non-null   float64
 1   Low        6704 non-null   float64
 2   Open       6704 non-null   float64
 3   Close      6704 non-null   float64
 4   Volume     6704 non-null   float64
 5   Adj Close  6704 non-null   float64
dtypes: float64(6)
memory usage: 366.6 KB


In [12]:
PG.head() #first five rows

High       Low      Open     Close     Volume  Adj Close
Date                                                                    
1995-01-03  15.62500  15.43750  15.46875  15.59375  3318400.0   8.063840
1995-01-04  15.65625  15.31250  15.53125  15.46875  2218800.0   7.999201
1995-01-05  15.43750  15.21875  15.37500  15.25000  2319600.0   7.886079
1995-01-06  15.40625  15.15625  15.15625  15.28125  3438000.0   7.902242
1995-01-09  15.40625  15.18750  15.34375  15.21875  1795200.0   7.869921

In [13]:
PG.tail() #last five rows

High         Low        Open       Close     Volume  \
Date                                                                    
2021-08-11  143.240005  142.470001  142.740005  142.619995  4205000.0   
2021-08-12  143.149994  142.350006  143.149994  142.949997  4956100.0   
2021-08-13  143.990005  142.690002  142.949997  143.639999  4888300.0   
2021-08-16  144.690002  143.380005  143.669998  144.639999  6040800.0   
2021-08-17  145.600006  143.889999  144.399994  144.880005  7577000.0   

             Adj Close  
Date                    
2021-08-11  142.619995  
2021-08-12  142.949997  
2021-08-13  143.639999  
2021-08-16  144.639999  
2021-08-17  144.880005

In [14]:
PG.head(20) #top 20 rows

High       Low      Open     Close     Volume  Adj Close
Date                                                                    
1995-01-03  15.62500  15.43750  15.46875  15.59375  3318400.0   8.063840
1995-01-04  15.65625  15.31250  15.53125  15.46875  2218800.0   7.999201
1995-01-05  15.43750  15.21875  15.37500  15.25000  2319600.0   7.886079
1995-01-06  15.40625  15.15625  15.15625  15.28125  3438000.0   7.902242
1995-01-09  15.40625  15.18750  15.34375  15.21875  1795200.0   7.869921
1995-01-10  15.43750  15.18750  15.28125  15.40625  4364000.0   7.966884
1995-01-11  15.59375  15.37500  15.59375  15.37500  3738400.0   7.950720
1995-01-12  15.53125  15.31250  15.37500  15.53125  3307600.0   8.031521
1995-01-13  15.84375  15.53125  15.59375  15.62500  3992800.0   8.125779
1995-01-16  15.96875  15.75000  15.90625  15.75000  3677200.0   8.190788
1995-01-17  15.81250  15.65625  15.71875  15.81250  2437600.0   8.223289
1995-01-18  15.75000  15.43750  15.68750  15.46875  3535200.0   8.044519
1995-01-19  15.40625  15.34375  15.34375  15.40625  2491200.0   8.012021
1995-01-20  15.40625  15.25000  15.40625  15.34375  5130800.0   7.979516
1995-01-23  15.50000  15.18750  15.18750  15.50000  3147200.0   8.060775
1995-01-24  15.53125  15.37500  15.50000  15.46875  2016400.0   8.044519
1995-01-25  15.78125  15.43750  15.50000  15.68750  2802400.0   8.158283
1995-01-26  15.84375  15.68750  15.71875  15.75000  3124000.0   8.190788
1995-01-27  16.25000  15.81250  15.81250  16.18750  6247200.0   8.418306
1995-01-30  16.56250  16.09375  16.12500  16.43750  5226400.0   8.548315

In [15]:
PG.tail(20) #last 20 rows

High         Low        Open       Close      Volume  \
Date                                                                     
2021-07-21  140.199997  138.990005  139.949997  139.199997   6954700.0   
2021-07-22  138.330002  136.710007  137.289993  137.800003   6013800.0   
2021-07-23  139.979996  137.080002  137.479996  139.789993   7906000.0   
2021-07-26  140.820007  139.220001  139.619995  140.279999   5925800.0   
2021-07-27  141.619995  140.000000  140.149994  140.850006   7075400.0   
2021-07-28  140.669998  138.710007  140.669998  138.759995   8520000.0   
2021-07-29  140.179993  138.729996  139.759995  139.479996   5430500.0   
2021-07-30  144.539993  141.550003  142.000000  142.229996  14393900.0   
2021-08-02  142.429993  140.800003  141.770004  141.880005   7009500.0   
2021-08-03  144.210007  141.520004  141.860001  143.949997   8455700.0   
2021-08-04  144.089996  142.350006  143.039993  142.429993   6628000.0   
2021-08-05  143.550003  141.470001  143.350006  142.500000   5363300.0   
2021-08-06  143.119995  141.220001  143.029999  141.410004   6030100.0   
2021-08-09  142.589996  141.699997  141.949997  142.179993   4743800.0   
2021-08-10  142.509995  141.660004  141.910004  142.270004   5253500.0   
2021-08-11  143.240005  142.470001  142.740005  142.619995   4205000.0   
2021-08-12  143.149994  142.350006  143.149994  142.949997   4956100.0   
2021-08-13  143.990005  142.690002  142.949997  143.639999   4888300.0   
2021-08-16  144.690002  143.380005  143.669998  144.639999   6040800.0   
2021-08-17  145.600006  143.889999  144.399994  144.880005   7577000.0   

             Adj Close  
Date                    
2021-07-21  138.329987  
2021-07-22  137.800003  
2021-07-23  139.789993  
2021-07-26  140.279999  
2021-07-27  140.850006  
2021-07-28  138.759995  
2021-07-29  139.479996  
2021-07-30  142.229996  
2021-08-02  141.880005  
2021-08-03  143.949997  
2021-08-04  142.429993  
2021-08-05  142.500000  
2021-08-06  141.410004  
2021-08-09  142.179993  
2021-08-10  142.270004  
2021-08-11  142.619995  
2021-08-12  142.949997  
2021-08-13  143.639999  
2021-08-16  144.639999  
2021-08-17  144.880005

In [ ]:
#To create a data set containing 5 columns representing adjusted closing prices of 5 different companies
#Procter&Gamble, Microsoft, AT&T, Ford, General Electrics
#Data : Adj Close

In [16]:
tickers = ['PG','MSFT','T','F','GE']
new_data = pd.DataFrame()  #empty dataframe

for i in tickers:
    new_data[i] = wb.DataReader( i, data_source = 'yahoo', start = '1995-1-1')['Adj Close']
new_data

#new_data['PG'] = wb.DataReader('PG', data_source='yahoo', start = '1995-1-1')['Adj Close']
#df['new'] = data['existing']

PG        MSFT          T          F          GE
Date                                                                
1995-01-03    8.063840    2.383754   5.877185   4.380183   32.931717
1995-01-04    7.999201    2.401081   5.843583   4.498034   32.931717
1995-01-05    7.886079    2.361476   5.934889   4.458752   33.012394
1995-01-06    7.902242    2.401081   5.934889   4.458752   32.850979
1995-01-09    7.869921    2.386229   5.916626   4.537320   32.528118
...                ...         ...        ...        ...         ...
2021-08-11  142.619995  286.950012  28.160000  13.930000  106.040001
2021-08-12  142.949997  289.809998  28.020000  13.900000  106.519997
2021-08-13  143.639999  292.850006  28.190001  13.590000  104.919998
2021-08-16  144.639999  294.600006  28.200001  13.460000  103.349998
2021-08-17  144.880005  293.079987  28.190001  12.990000  101.620003

[6704 rows x 5 columns]

In [17]:
new_data.tail()

PG        MSFT          T      F          GE
Date                                                            
2021-08-11  142.619995  286.950012  28.160000  13.93  106.040001
2021-08-12  142.949997  289.809998  28.020000  13.90  106.519997
2021-08-13  143.639999  292.850006  28.190001  13.59  104.919998
2021-08-16  144.639999  294.600006  28.200001  13.46  103.349998
2021-08-17  144.880005  293.079987  28.190001  12.99  101.620003

In [ ]:
#IEX does not provide data for more than 5 years prior to the data in which you execute the code

In [25]:
#pip3 install quandl
import quandl

In [ ]:
mydata1 = quandl.get("FRED/GDP")

In [28]:
mydata1.head()

NameError: name 'mydata1' is not defined

In [27]:
#saving this data to csv file
import pandas as pd

In [29]:
#data-to-convert.to_csv('path/give-a-filename.csv')
PG.to_csv('C:/Aditi/My Work/Udemy/Finance Python/example1.csv')

In [31]:
#import a csv file
PG = pd.read_csv('C:/Aditi/My Work/Udemy/Finance Python/example1.csv')
PG.head()

Date      High       Low      Open     Close     Volume  Adj Close
0  1995-01-03  15.62500  15.43750  15.46875  15.59375  3318400.0   8.063840
1  1995-01-04  15.65625  15.31250  15.53125  15.46875  2218800.0   7.999201
2  1995-01-05  15.43750  15.21875  15.37500  15.25000  2319600.0   7.886079
3  1995-01-06  15.40625  15.15625  15.15625  15.28125  3438000.0   7.902242
4  1995-01-09  15.40625  15.18750  15.34375  15.21875  1795200.0   7.869921

In [32]:
#exporting data as an excel file
#data-to-convert.to_excel('path/give-a-name.xlsx')
PG.to_excel('C:/Aditi/My Work/Udemy/Finance Python/example2.xlsx')

# Changing the Index of your Time-Series Data

In [33]:
mydata2 = pd.read_csv('C:/Aditi/My Work/Udemy/Finance Python/Data_02.csv')

In [34]:
mydata2

Date    Open      High     Low     Close       Volume  \
0     2017-03-03  136.63  137.3300  136.08  137.1300   11095605.0   
1     2017-03-02  137.09  137.8200  136.31  136.7603   12243028.0   
2     2017-03-01  136.47  137.4800  136.30  137.4200   16257010.0   
3     2017-02-28  136.79  136.8050  134.75  135.5400   16112092.0   
4     2017-02-27  135.26  137.1846  135.02  136.4100   14306668.0   
...          ...     ...       ...     ...       ...          ...   
1200  2012-05-24   32.95   33.2100   31.77   33.0300   50237200.0   
1201  2012-05-23   31.37   32.5000   31.36   32.0000   73600000.0   
1202  2012-05-22   32.61   33.5900   30.94   31.0000  101786600.0   
1203  2012-05-21   36.53   36.6600   33.00   34.0300  168192700.0   
1204  2012-05-18   42.05   45.0000   38.00   38.2318  573576400.0   

      Ex-Dividend  Split Ratio  Adj. Open  Adj. High  Adj. Low  Adj. Close  \
0             0.0          1.0     136.63   137.3300    136.08    137.1300   
1             0.0          1.0     137.09   137.8200    136.31    136.7603   
2             0.0          1.0     136.47   137.4800    136.30    137.4200   
3             0.0          1.0     136.79   136.8050    134.75    135.5400   
4             0.0          1.0     135.26   137.1846    135.02    136.4100   
...           ...          ...        ...        ...       ...         ...   
1200          0.0          1.0      32.95    33.2100     31.77     33.0300   
1201          0.0          1.0      31.37    32.5000     31.36     32.0000   
1202          0.0          1.0      32.61    33.5900     30.94     31.0000   
1203          0.0          1.0      36.53    36.6600     33.00     34.0300   
1204          0.0          1.0      42.05    45.0000     38.00     38.2318   

      Adj. Volume  
0      11095605.0  
1      12243028.0  
2      16257010.0  
3      16112092.0  
4      14306668.0  
...           ...  
1200   50237200.0  
1201   73600000.0  
1202  101786600.0  
1203  168192700.0  
1204  573576400.0  

[1205 rows x 13 columns]

In [35]:
#To set dates as the index
mydata2 = pd.read_csv('C:/Aditi/My Work/Udemy/Finance Python/Data_02.csv', index_col='Date')

In [36]:
mydata2

Open      High     Low     Close       Volume  Ex-Dividend  \
Date                                                                       
2017-03-03  136.63  137.3300  136.08  137.1300   11095605.0          0.0   
2017-03-02  137.09  137.8200  136.31  136.7603   12243028.0          0.0   
2017-03-01  136.47  137.4800  136.30  137.4200   16257010.0          0.0   
2017-02-28  136.79  136.8050  134.75  135.5400   16112092.0          0.0   
2017-02-27  135.26  137.1846  135.02  136.4100   14306668.0          0.0   
...            ...       ...     ...       ...          ...          ...   
2012-05-24   32.95   33.2100   31.77   33.0300   50237200.0          0.0   
2012-05-23   31.37   32.5000   31.36   32.0000   73600000.0          0.0   
2012-05-22   32.61   33.5900   30.94   31.0000  101786600.0          0.0   
2012-05-21   36.53   36.6600   33.00   34.0300  168192700.0          0.0   
2012-05-18   42.05   45.0000   38.00   38.2318  573576400.0          0.0   

            Split Ratio  Adj. Open  Adj. High  Adj. Low  Adj. Close  \
Date                                                                  
2017-03-03          1.0     136.63   137.3300    136.08    137.1300   
2017-03-02          1.0     137.09   137.8200    136.31    136.7603   
2017-03-01          1.0     136.47   137.4800    136.30    137.4200   
2017-02-28          1.0     136.79   136.8050    134.75    135.5400   
2017-02-27          1.0     135.26   137.1846    135.02    136.4100   
...                 ...        ...        ...       ...         ...   
2012-05-24          1.0      32.95    33.2100     31.77     33.0300   
2012-05-23          1.0      31.37    32.5000     31.36     32.0000   
2012-05-22          1.0      32.61    33.5900     30.94     31.0000   
2012-05-21          1.0      36.53    36.6600     33.00     34.0300   
2012-05-18          1.0      42.05    45.0000     38.00     38.2318   

            Adj. Volume  
Date                     
2017-03-03   11095605.0  
2017-03-02   12243028.0  
2017-03-01   16257010.0  
2017-02-28   16112092.0  
2017-02-27   14306668.0  
...                 ...  
2012-05-24   50237200.0  
2012-05-23   73600000.0  
2012-05-22  101786600.0  
2012-05-21  168192700.0  
2012-05-18  573576400.0  

[1205 rows x 12 columns]

In [39]:
mydata3 = pd.read_excel('C:/Aditi/My Work/Udemy/Finance Python/Data_03.xlsx')
mydata3

Year     Gas Exp     Pop        Gasp  Income
0   1953    7.400000  159565   16.667999    8883
1   1954    7.800000  162391   17.028999    8685
2   1955    8.600000  165275   17.209999    9137
3   1956    9.400000  168221   17.729000    9436
4   1957   10.200000  171274   18.497000    9534
5   1958   10.600000  174141   18.316000    9343
6   1959   11.300000  177130   18.576000    9738
7   1960   12.000000  180760   19.112000    9770
8   1961   12.000000  183742   18.924000    9843
9   1962   12.600000  186590   19.042999   10226
10  1963   13.000000  189300   18.997000   10398
11  1964   13.600000  191927   18.872999   11051
12  1965   14.800000  194347   19.587000   11430
13  1966   16.000000  196599   20.038000   11981
14  1967   17.100000  198752   20.700001   12418
15  1968   18.600000  200745   21.004999   12932
16  1969   20.500000  202736   21.695999   13060
17  1970   21.900000  205089   21.889999   13567
18  1971   23.200001  207692   22.049999   14008
19  1972   24.400000  209924   22.336000   14270
20  1973   28.100000  211939   24.473000   15309
21  1974   36.099998  213898   33.058998   15074
22  1975   39.700001  215981   35.278000   15555
23  1976   43.000000  218086   36.777000   15693
24  1977   46.900002  220289   38.907001   15991
25  1978   50.099998  222629   40.597000   16674
26  1979   66.199997  225106   54.405998   16843
27  1980   86.699997  227726   75.509003   16711
28  1981   97.900002  230008   84.017998   17046
29  1982   94.099998  232218   79.767998   17429
30  1983   93.099998  234333   77.160004   17659
31  1984   94.599998  236394   76.004997   18922
32  1985   97.199997  238506   76.619003   19622
33  1986   80.099998  240683   60.174999   19944
34  1987   85.400002  242843   62.487999   19802
35  1988   88.300003  245061   63.016998   20682
36  1989   98.599998  247387   68.836998   21048
37  1990  111.199997  250181   78.385002   21379
38  1991  108.500000  253530   77.337997   21129
39  1992  112.400002  256922   77.040001   21505
40  1993  114.099998  260282   76.257004   21515
41  1994  116.199997  263455   76.613998   21797
42  1995  120.199997  266588   77.825996   22100
43  1996  130.399994  269714   82.596001   22506
44  1997  134.399994  272958   82.579002   22944
45  1998  122.400002  276154   71.874001   24079
46  1999  137.899994  279328   78.207001   24464
47  2000  175.699997  282429  100.000000   25380
48  2001  171.600006  285366   96.289001   25449
49  2002  163.399994  288217   90.404999   26352
50  2003  191.300003  291073  105.153999   26437
51  2004  224.500000  293951  123.901001   27113

In [40]:
mydata3.set_index('Year')
#set_index will just display the data with the index you have indicated

Gas Exp     Pop        Gasp  Income
Year                                        
1953    7.400000  159565   16.667999    8883
1954    7.800000  162391   17.028999    8685
1955    8.600000  165275   17.209999    9137
1956    9.400000  168221   17.729000    9436
1957   10.200000  171274   18.497000    9534
1958   10.600000  174141   18.316000    9343
1959   11.300000  177130   18.576000    9738
1960   12.000000  180760   19.112000    9770
1961   12.000000  183742   18.924000    9843
1962   12.600000  186590   19.042999   10226
1963   13.000000  189300   18.997000   10398
1964   13.600000  191927   18.872999   11051
1965   14.800000  194347   19.587000   11430
1966   16.000000  196599   20.038000   11981
1967   17.100000  198752   20.700001   12418
1968   18.600000  200745   21.004999   12932
1969   20.500000  202736   21.695999   13060
1970   21.900000  205089   21.889999   13567
1971   23.200001  207692   22.049999   14008
1972   24.400000  209924   22.336000   14270
1973   28.100000  211939   24.473000   15309
1974   36.099998  213898   33.058998   15074
1975   39.700001  215981   35.278000   15555
1976   43.000000  218086   36.777000   15693
1977   46.900002  220289   38.907001   15991
1978   50.099998  222629   40.597000   16674
1979   66.199997  225106   54.405998   16843
1980   86.699997  227726   75.509003   16711
1981   97.900002  230008   84.017998   17046
1982   94.099998  232218   79.767998   17429
1983   93.099998  234333   77.160004   17659
1984   94.599998  236394   76.004997   18922
1985   97.199997  238506   76.619003   19622
1986   80.099998  240683   60.174999   19944
1987   85.400002  242843   62.487999   19802
1988   88.300003  245061   63.016998   20682
1989   98.599998  247387   68.836998   21048
1990  111.199997  250181   78.385002   21379
1991  108.500000  253530   77.337997   21129
1992  112.400002  256922   77.040001   21505
1993  114.099998  260282   76.257004   21515
1994  116.199997  263455   76.613998   21797
1995  120.199997  266588   77.825996   22100
1996  130.399994  269714   82.596001   22506
1997  134.399994  272958   82.579002   22944
1998  122.400002  276154   71.874001   24079
1999  137.899994  279328   78.207001   24464
2000  175.699997  282429  100.000000   25380
2001  171.600006  285366   96.289001   25449
2002  163.399994  288217   90.404999   26352
2003  191.300003  291073  105.153999   26437
2004  224.500000  293951  123.901001   27113

In [41]:
mydata3 = mydata3.set_index('Year') #store it

In [42]:
mydata3

Gas Exp     Pop        Gasp  Income
Year                                        
1953    7.400000  159565   16.667999    8883
1954    7.800000  162391   17.028999    8685
1955    8.600000  165275   17.209999    9137
1956    9.400000  168221   17.729000    9436
1957   10.200000  171274   18.497000    9534
1958   10.600000  174141   18.316000    9343
1959   11.300000  177130   18.576000    9738
1960   12.000000  180760   19.112000    9770
1961   12.000000  183742   18.924000    9843
1962   12.600000  186590   19.042999   10226
1963   13.000000  189300   18.997000   10398
1964   13.600000  191927   18.872999   11051
1965   14.800000  194347   19.587000   11430
1966   16.000000  196599   20.038000   11981
1967   17.100000  198752   20.700001   12418
1968   18.600000  200745   21.004999   12932
1969   20.500000  202736   21.695999   13060
1970   21.900000  205089   21.889999   13567
1971   23.200001  207692   22.049999   14008
1972   24.400000  209924   22.336000   14270
1973   28.100000  211939   24.473000   15309
1974   36.099998  213898   33.058998   15074
1975   39.700001  215981   35.278000   15555
1976   43.000000  218086   36.777000   15693
1977   46.900002  220289   38.907001   15991
1978   50.099998  222629   40.597000   16674
1979   66.199997  225106   54.405998   16843
1980   86.699997  227726   75.509003   16711
1981   97.900002  230008   84.017998   17046
1982   94.099998  232218   79.767998   17429
1983   93.099998  234333   77.160004   17659
1984   94.599998  236394   76.004997   18922
1985   97.199997  238506   76.619003   19622
1986   80.099998  240683   60.174999   19944
1987   85.400002  242843   62.487999   19802
1988   88.300003  245061   63.016998   20682
1989   98.599998  247387   68.836998   21048
1990  111.199997  250181   78.385002   21379
1991  108.500000  253530   77.337997   21129
1992  112.400002  256922   77.040001   21505
1993  114.099998  260282   76.257004   21515
1994  116.199997  263455   76.613998   21797
1995  120.199997  266588   77.825996   22100
1996  130.399994  269714   82.596001   22506
1997  134.399994  272958   82.579002   22944
1998  122.400002  276154   71.874001   24079
1999  137.899994  279328   78.207001   24464
2000  175.699997  282429  100.000000   25380
2001  171.600006  285366   96.289001   25449
2002  163.399994  288217   90.404999   26352
2003  191.300003  291073  105.153999   26437
2004  224.500000  293951  123.901001   27113